In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [64]:
train=pd.read_csv("Train_UWu5bXk.csv")
test=pd.read_csv("Test_u94Q5KV.csv")

In [65]:
train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [60]:
pd.crosstab(train.Item_Identifier,train.Item_Type)

Item_Type,Baking Goods,Breads,Breakfast,Canned,Dairy,Frozen Foods,Fruits and Vegetables,Hard Drinks,Health and Hygiene,Household,Meat,Others,Seafood,Snack Foods,Soft Drinks,Starchy Foods
Item_Identifier,,,,,,,,,,,,,,,,
DRA12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0
DRA24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0
DRA59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0
DRB01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0
DRB13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0
DRB24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0
DRB25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0
DRB48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0
DRC01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0
DRC12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0
DRC13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0
DRC24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0
DRC25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0
DRC27,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0
DRC36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0
DRC49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0
DRD01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0
DRD12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0
DRD13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0
DRD15,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0
DRD24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0
DRD25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0
DRD27,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0
DRD37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0
DRD49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0
DRD60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0
DRE01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0
DRE03,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0
DRE12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0
DRE13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NCX05,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0
NCX06,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0
NCX17,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0
NCX18,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0
NCX29,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0
NCX30,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0
NCX41,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0
NCX42,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0
NCX53,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
NCX54,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0
NCY05,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0
NCY06,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0
NCY17,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0
NCY18,0,0,0,0,0,0,0,0,0,9,0,0,0,0,0,0
NCY29,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0
NCY30,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0
NCY41,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0
NCY42,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0
NCY53,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0
NCY54,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0
NCZ05,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0
NCZ06,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0
NCZ17,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0
NCZ18,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0
NCZ29,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0
NCZ30,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0
NCZ41,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0
NCZ42,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0
NCZ53,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0
NCZ54,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0

In [6]:
train.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [4]:
train.count()

Item_Identifier              8523
Item_Weight                  7060
Item_Fat_Content             8523
Item_Visibility              8523
Item_Type                    8523
Item_MRP                     8523
Outlet_Identifier            8523
Outlet_Establishment_Year    8523
Outlet_Size                  6113
Outlet_Location_Type         8523
Outlet_Type                  8523
Item_Outlet_Sales            8523
dtype: int64

In [62]:
train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [43]:
train.Item_Fat_Content.value_counts()

Low Fat    5517
Regular    3006
Name: Item_Fat_Content, dtype: int64

In [42]:
train.Item_Fat_Content=train.Item_Fat_Content.replace('low fat','Low Fat')
train.Item_Fat_Content=train.Item_Fat_Content.replace('LF','Low Fat')
train.Item_Fat_Content=train.Item_Fat_Content.replace('reg','Regular')

In [11]:
x=train.Item_Type.value_counts()
type(x)

pandas.core.series.Series

In [35]:
x=train.Item_Type.unique()
type(x)
train.Item_Type.unique=list(enumerate(x))

In [36]:
train.Item_Type.value_counts()

Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: Item_Type, dtype: int64

In [44]:
train.Outlet_Identifier.value_counts()

OUT027    935
OUT013    932
OUT035    930
OUT046    930
OUT049    930
OUT045    929
OUT018    928
OUT017    926
OUT010    555
OUT019    528
Name: Outlet_Identifier, dtype: int64

In [45]:
train.Outlet_Location_Type.value_counts()

Tier 3    3350
Tier 2    2785
Tier 1    2388
Name: Outlet_Location_Type, dtype: int64

In [46]:
train.Outlet_Type.value_counts()

Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: Outlet_Type, dtype: int64

In [47]:
train.Outlet_Size.value_counts()

Medium    2793
Small     2388
High       932
Name: Outlet_Size, dtype: int64

In [48]:
train.Outlet_Establishment_Year.value_counts()

1985    1463
1987     932
1999     930
1997     930
2004     930
2002     929
2009     928
2007     926
1998     555
Name: Outlet_Establishment_Year, dtype: int64

In [51]:
pd.crosstab(train.Outlet_Establishment_Year,train.Outlet_Type)

Outlet_Type,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3
Outlet_Establishment_Year,,,,
1985,528,0,0,935
1987,0,932,0,0
1997,0,930,0,0
1998,555,0,0,0
1999,0,930,0,0
2002,0,929,0,0
2004,0,930,0,0
2007,0,926,0,0
2009,0,0,928,0

In [52]:
pd.crosstab(train.Outlet_Type,train.Outlet_Location_Type)

Outlet_Location_Type  Tier 1  Tier 2  Tier 3
Outlet_Type
Grocery Store            528       0     555
Supermarket Type1       1860    2785     932
Supermarket Type2          0       0     928
Supermarket Type3          0       0     935

In [53]:
pd.crosstab(train.Outlet_Location_Type,train.Outlet_Identifier)

Outlet_Identifier,OUT010,OUT013,OUT017,OUT018,OUT019,OUT027,OUT035,OUT045,OUT046,OUT049
Outlet_Location_Type,,,,,,,,,,
Tier 1,0,0,0,0,528,0,0,0,930,930
Tier 2,0,0,926,0,0,0,930,929,0,0
Tier 3,555,932,0,928,0,935,0,0,0,0

In [58]:
pd.crosstab(train.Outlet_Establishment_Year,train.Outlet_Identifier)

Outlet_Identifier,OUT010,OUT013,OUT017,OUT018,OUT019,OUT027,OUT035,OUT045,OUT046,OUT049
Outlet_Establishment_Year,,,,,,,,,,
1985,0,0,0,0,528,935,0,0,0,0
1987,0,932,0,0,0,0,0,0,0,0
1997,0,0,0,0,0,0,0,0,930,0
1998,555,0,0,0,0,0,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,930
2002,0,0,0,0,0,0,0,929,0,0
2004,0,0,0,0,0,0,930,0,0,0
2007,0,0,926,0,0,0,0,0,0,0
2009,0,0,0,928,0,0,0,0,0,0